server:
  port: ${SERVER_PORT}
  address: 0.0.0.0
  servlet:
    context-path: /profile

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 2
      timeout: ${REDIS_TIME_OUT}
      lettuce:
        pool:
          max-active: ${MAX_ACTIVE}
          max-idle: ${MAX_IDLE}
          min-idle: ${MIN_IDLE}

  cache:
    type: redis

app:
  services:
    identity: ${IDENTITY_SERVICE_URL}
    notification: ${NOTIFICATION_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always