server:
  port: ${SERVER_PORT}
  address: 0.0.0.0
  servlet:
    context-path: /post

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 1
      timeout: ${REDIS_TIME_OUT}
      lettuce:
        pool:
          max-active: ${MAX_ACTIVE}
          max-idle: ${MAX_IDLE}
          min-idle: ${MIN_IDLE}

  cache:
    type: redis
    redis:
      time-to-live: ${TIME_TO_LIVE}
      cache-null-values: false
      use-key-prefix: true
      key-prefix: ${REDIS_KEY_PREFIX}
      enable-statistics: true

app:
  service:
    profile:
      url: ${PROFILE_SERVICE_URL}
    notification:
      url: ${NOTIFICATION_SERVICE_URL}
    identity:
      url: ${IDENTITY_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always