server:
  port: ${SERVER_PORT}
  address: 0.0.0.0
  servlet:
    context-path: /stories

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  service:
    identity:
      url: ${IDENTITY_SERVICE_URL}
    profile:
      url: ${PROFILE_SERVICE_URL}
    notification:
      url: ${NOTIFICATION_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always