server:
  port: ${SERVER_PORT}
  address: 0.0.0.0
  servlet:
    context-path: /chat

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIME_OUT}
      lettuce:
        pool:
          max-active: ${MAX_ACTIVE}
          max-idle: ${MAX_IDLE}
          min-idle: ${MIN_IDLE}
  cache:
    type: redis
    redis:
      time-to-live: ${TIME_TO_LIVE}
      cache-null-values: false
      use-key-prefix: true
      key-prefix: ${REDIS_KEY_PREFIX}
      enable-statistics: true
  websocket:
    enabled: true

app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL}
    identity:
      url: ${IDENTITY_SERVICE_URL}
    ai:
      url: ${AI_SERVICE_URL}
  call:
    ring-timeout: 60 #seconds
    max-duration: 3600

